print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/Guest/WithoutSalt/Assets/Mesh/columnMesh.ma"`)
{		
	file -o "/Users/Guest/WithoutSalt/Assets/Mesh/columnMesh.ma";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/Guest/WithoutSalt/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";


system ("rm \"/Users/Guest/WithoutSalt/Temp/CommandPipe\"");

$donepipeKill = `fopen "/Users/Guest/WithoutSalt/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
